[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "python"
version = "0.1.0"
description = "Survey of Python 3 features and libraries, with a strong focus on using type hints."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []